config/routes.rb
Urlshortener::Application.routes.draw do
  resources :urls, :only => [:show, :new, :create, :index]
  match  '*path', :to => 'urls#ident'
  root :to => redirect('/urls/new')

end

app/models/url.rb
require 'base64'
class Url < ActiveRecord::Base
  attr_accessible :url
  validates :url, :presence => true
  attr_accessible :key
  validates :key, :presence => true
  
  before_validation :set_key
  def set_key
	base64 = Base64.encode64(url)
	write_attribute(:key, base64)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
	@shortened_url = Url.new
	@short_urls = Url.find(:all)
  end
  def create
	@shortened_url = Url.new(params[:url])
	#@shortened_url.key = ActiveSupport::Base64.encode64(@shortened_url.url)
	if @shortened_url.save
		flash[:shortened_id] = @shortened_url.id
		flash[:count] = @shortened_url.count
		flash[:org] = @shortened_url.url
		flash[:short_url] = @shortened_url.key
		redirect_to new_url_url
	else
		render :action => "new"
	end
  end
  def show
	@shortened_url = Url.where("key = ?", params[:key]).first
	@shortened_url.increment!(:count)
	redirect_to @shortened_url.url
  end
  def index
	@short_urls = Url.find(:all)
  end
  def ident
  @url = Url.where(:key => params['key']).first
	if @url
		redirect_to(@url.url)
	else
		render :text => "not found: #{params['key']}", :status => 404
	end
  end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Urlshortener</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:shortened_id].present? %>
	<p class='shortened-link'>
		The shortened url for <%= flash[:org] %> is available here:
		<%= link_to url_url(flash[:key]), url_url(flash[:key]) %>.
		The link has been used <%= flash[:count] %> times.
	</p>
<%end%>
<%= yield %>
	<p class='index-links'>
	<li><strong>List of URLs</strong></li>
		<%if @short_urls %>
		<table>
		<% for url in @short_urls %>
			<tr>
			<td>Original Url: <%=url.url%></td>
			<td>Shortened Url: <%= link_to url_url(url.key), url_url(url.key)%></td>
			<td>Usage count: <%=url.count%></td>
			</tr>
		<%end%>	
		<%end%>
		</table>
	</p>
</body>
</html>

app/views/urls/new.html.erb
<h1>Add a new URL</h1>
<%= form_for @shortened_url do |form| %>
  <p>
    <%= form.label :url, "Input URL to be shortened:" %>
    <%= form.text_field :url %>
  </p>
  <% if @shortened_url.errors[:url].any? %>
    <p class='error-messages'>
      The given url <%= @shortened_url.errors[:url].to_sentence %>.
    </p>
  <% end %>
  <p class='buttons'>
    <%= form.submit "Shorten my URL" %>
  </p>
<% end %>